Parameters:
  App:
    Type: String
  Env:
    Type: String
  VPCID:
    Type: AWS::EC2::VPC::Id
  PrivateSubnets:
    Type: CommaDelimitedList
  VPCCidr:
    Type: String

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub "Subnet group for ${App}-${Env}"
      SubnetIds: !Ref PrivateSubnets

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub "DB Security Group for ${App}-${Env}"
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: !Ref VPCCidr

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/copilot/${App}/${Env}/secrets/DB_CREDENTIALS"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "dbadmin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '/@" '

  DatabaseURLSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "/copilot/${App}/${Env}/secrets/DATABASE_URL"
      SecretString: !Sub 'postgresql://dbadmin:{{resolve:secretsmanager:${DBSecret}:SecretString:password}}@${RDSInstance.Endpoint.Address}:${RDSInstance.Endpoint.Port}/marketdb'

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${App}-${Env}-rds-instance"
      DBName: "marketdb"
      AllocatedStorage: 20
      DBInstanceClass: db.t4g.micro
      Engine: postgres
      EngineVersion: "16"
      MasterUsername: "dbadmin"
      MasterUserPassword: !Sub '{{resolve:secretsmanager:${DBSecret}:SecretString:password}}'
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
      PubliclyAccessible: false
      BackupRetentionPeriod: 1
      StorageType: gp2
      StorageEncrypted: true
      MultiAZ: false

Outputs:
  DatabaseEndpoint:
    Description: RDS instance endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub "${App}-${Env}-DatabaseEndpoint"
  
  DatabasePort:
    Description: RDS instance port
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: !Sub "${App}-${Env}-DatabasePort"
  
  DatabaseName:
    Description: Database name
    Value: "marketdb"
    Export:
      Name: !Sub "${App}-${Env}-DatabaseName"
  
  DatabaseSecretArn:
    Description: Database credentials secret ARN
    Value: !Ref DBSecret
    Export:
      Name: !Sub "${App}-${Env}-DatabaseSecretArn"
  
  DatabaseURLSecretArn:
    Description: Database URL secret ARN
    Value: !Ref DatabaseURLSecret
    Export:
      Name: !Sub "${App}-${Env}-DatabaseURLSecretArn"
  
  DBSecurityGroupId:
    Description: Database security group ID
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub "${App}-${Env}-DBSecurityGroupId" 