Parameters:
  App:
    Type: String
  Env:
    Type: String
  VPCID:
    Type: AWS::EC2::VPC::Id
  PrivateSubnets:
    Type: CommaDelimitedList
  VPCCidr:
    Type: String
    Default: "10.0.0.0/16"

Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Copilot RDS Subnet Group"
      SubnetIds: !Ref PrivateSubnets

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Copilot RDS access"
      VpcId: !Ref VPCID

  DBSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref DBSecurityGroup
      IpProtocol: tcp
      FromPort: 5432
      ToPort: 5432
      CidrIp: !Ref VPCCidr

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: !Sub "Postgres credentials for ${App}-${Env}"
      GenerateSecretString:
        SecretStringTemplate: '{"username": "postgres"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludePunctuation: true

  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub "${App}-${Env}-rds-instance"
      DBName: "marketdb"
      AllocatedStorage: 25
      DBInstanceClass: db.t3.medium
      Engine: postgres
      EngineVersion: "12"
      MasterUsername: "postgres"
      MasterUserPassword: !Join ["", ["{{resolve:secretsmanager:", !Ref DBSecret, ":SecretString:password}}"]]
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      PubliclyAccessible: false
      BackupRetentionPeriod: 1
      StorageType: gp2
      MultiAZ: false

Outputs:
  marketdbSecret:
    Description: "Secret ARN with credentials"
    Value: !Ref DBSecret
    Export:
      Name: !Sub "${App}-${Env}-marketdbSecret"

  marketdbSecurityGroup:
    Description: "Security Group for RDS"
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub "${App}-${Env}-marketdbSecurityGroup"

  marketdbEndpoint:
    Description: "Database endpoint address"
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub "${App}-${Env}-marketdbEndpoint" 