"""Add series_ticker column to markets table

Revision ID: dd865a71bb91
Revises: 82edbd9086e5
Create Date: 2025-07-26 13:40:59.649402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd865a71bb91'
down_revision: Union[str, None] = '82edbd9086e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('series_ticker', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_markets_series_ticker'), 'markets', ['series_ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_series_ticker'), table_name='markets')
    op.drop_column('markets', 'series_ticker')
    # ### end Alembic commands ###
