"""Initial migration

Revision ID: 82edbd9086e5
Revises: 
Create Date: 2025-07-17 12:47:55.779260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82edbd9086e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Integer(), nullable=True),
    sa.Column('liquidity', sa.Integer(), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=True),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('expiration_time', sa.DateTime(), nullable=True),
    sa.Column('resolution_rules', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_markets_liquidity', 'markets', ['liquidity'], unique=False)
    op.create_index('idx_markets_open_time', 'markets', ['open_time'], unique=False)
    op.create_index('idx_markets_status_category', 'markets', ['status', 'category'], unique=False)
    op.create_index(op.f('ix_markets_category'), 'markets', ['category'], unique=False)
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_index(op.f('ix_markets_ticker'), 'markets', ['ticker'], unique=True)
    op.create_table('market_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('change_window_days', sa.Integer(), nullable=False),
    sa.Column('price_change', sa.Float(), nullable=False),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('change_percentage', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_changes_calculated_at', 'market_changes', ['calculated_at'], unique=False)
    op.create_index('idx_market_changes_market_window', 'market_changes', ['market_id', 'change_window_days'], unique=False)
    op.create_index('idx_market_changes_price_change', 'market_changes', ['price_change'], unique=False)
    op.create_index(op.f('ix_market_changes_id'), 'market_changes', ['id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_history_market_timestamp', 'price_history', ['market_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index('idx_price_history_market_timestamp', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_market_changes_id'), table_name='market_changes')
    op.drop_index('idx_market_changes_price_change', table_name='market_changes')
    op.drop_index('idx_market_changes_market_window', table_name='market_changes')
    op.drop_index('idx_market_changes_calculated_at', table_name='market_changes')
    op.drop_table('market_changes')
    op.drop_index(op.f('ix_markets_ticker'), table_name='markets')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_category'), table_name='markets')
    op.drop_index('idx_markets_status_category', table_name='markets')
    op.drop_index('idx_markets_open_time', table_name='markets')
    op.drop_index('idx_markets_liquidity', table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
